### ISSUE TITLE
Could not get it to work

### ISSUE THREAD

**Issue by BKSpurgeon** [jeremyevans/rodauth-demo-rails#1]
Hi Jeremy

Am trying to get RodAuth to work using the rails example you've given. I cannot get it to work. 
Here are my files with replication instructions:  https://github.com/BKSpurgeon/rodauth-demo-rails  - any pointers would be much appreciated. Or alternatively, I should I scrap this example, and just start from scratch with a rails 6 demo?

Secondly, I do note that you have made use of the https://github.com/jeremyevans/roda-rails/blob/master/lib/roda/plugins/rails42.rb plugin. Am interested to update it for rails 6 but I don't know what to test -- any general pointers in the right direction would be appreciated. I can put in a PR after I solve this issue, if that would help.

regards

Ben

**Comment by jeremyevans** [comment]
You probably want to start from scratch, and use this only as an example.  There have probably been a lot of changes in Rails in the last 4 years that may have broken this.

I haven't used Rails in over 5 years and don't really want to start using it again, so unfortunately you are kind of on your own if you want to integrate Rails and Rodauth.
